export const initialState = {
    user: null,
    allUsers: null,
    allSongs: null,
    editSongs: null,
    typeForNew: null,
    typeAlbumArtistSong:null,
    allArtists: null,
    editArtists: null,
    allAlbums: null,
    editAlbum:null,
    filterTerm: "all",
    artistFilter: null,
    languageFilter: null,
    albumFilter: null,
    alertType: null,
    isSongPlaying: false,
    songIndex: 0,
    roleFilter: null,
    miniPlayer: false,
    allProfit: null,
    page: null,
    rowsPerPage: null,
    searchSong: null
}